version: '3.4'

services:
  Agateway:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: ./GatewayAPI/Dockerfile
    ports: 
      - 8280:8080
    environment:
      - NODES_LOCATION=http://100.80.248.138:8080, http://100.112.33.3:8080, http://100.112.33.3:8080

  raftgateway:
    image: ${DOCKER_REGISTRY-}raftgateway
    build:
      context: .
      dockerfile: ./RaftGateway/Dockerfile
    

  Anode1:
    image: ${DOCKER_REGISTRY-}raftnodesapi
    build:
      context: .
      dockerfile: ./RaftNodesAPI/Dockerfile
    ports:
      - 8282:8080
    environment:
      - NODES_LOCATION= http://100.112.33.3:8080, http://100.112.33.3:8080 
    