version: '3.4'

services:
 
  Anode2:
    image: ${DOCKER_REGISTRY-}raftnodesapi
    build:
      context: .
      dockerfile: ./RaftNodesAPI/Dockerfile
    ports: 
      - 8283:8080
    environment:
      - NODES_LOCATION= http://100.80.248.138:8080, http://100.112.33.3:8080

  Anode3:
    image: ${DOCKER_REGISTRY-}raftnodesapi
    build:
      context: .
      dockerfile: ./RaftNodesAPI/Dockerfile
    ports:
      - 8284:8080
    environment:
      - NODES_LOCATION= http://100.80.248.138:8080, http://100.112.33.3:8080