 name: GitHub Actions
 
 on: [push]
       
 jobs:
   Run-server-2:
     runs-on: server-1
     steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Setup .NET 8
         uses: actions/setup-dotnet@v1
         with:
           dotnet-version: 8.0.x
           include-prerelease: true

       - name: redeploy application
         run: |
             docker compose -f docker-compose.yml build --no-cache 
             docker compose -f docker-compose.yml down
             docker compose -f docker-compose.yml up -d

       - name: Tests
         run: |
           cd RaftElectionTest
           dotnet test
   Run-server-4:
     runs-on: server-4
     steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Setup .NET 8
         uses: actions/setup-dotnet@v1
         with:
           dotnet-version: 8.0.x
           include-prerelease: true


       - name: redeploy application
         run: |
             docker compose -f docker-compose-0.yml build --no-cache 
             docker compose -f docker-compose-0.yml down
             docker compose -f docker-compose-0.yml up -d
       - name: Tests
         run: |
           cd RaftElectionTest
           dotnet test
