 name: GitHub Actions
 
 on: 
   push:
     branches:
       - main
       
 jobs:
   Explore-GitHub-Actions:
     runs-on: self-hosted
     steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Setup .NET 8
         uses: actions/setup-dotnet@v1
         with:
           dotnet-version: 8.0.x
           include-prerelease: true


       - name: redeploy application
         run: |
             docker compose pull
             docker compose build --no-cache 
             docker compose down
             docker compose up -d
       - name: Tests
         run: |
           cd RaftElectionTest
           dotnet test
